### ISSUE TITLE
Question about downloading outdoor scenes for nerf training

### ISSUE THREAD

**Issue by shenyehui** [DL3DV-10K/Dataset#5]
Thanks for the great work!  I want to download some outdoor scenes data for nerf training, can I just run it directly with this code? #python download.py --odir DL3DV-10K --subset 1K --resolution 960P --file_type images+poses --clean_ cache

**Comment by ShengCN** [comment]
Hi @shenyehui, this code is used to download the 0~1K batch with 960P resolution. We have not provided the script for only downloading outdoor scenes yet. 

But one solution is this: 

1. Find outdoor scene from our preview page: https://htmlpreview.github.io/?https://github.com/DL3DV-10K/Dataset/blob/main/visualize/index.html. You can search all unbd (unbounded) rows to find the hashes 
2. Then write a script using download.py to download the scenes by hash 

As you are mentioning NeRF, maybe you can also refer to the benchmark [repo](https://huggingface.co/datasets/DL3DV/DL3DV-Benchmark). See this [file](https://huggingface.co/datasets/DL3DV/DL3DV-Benchmark/blob/main/benchmark-meta.csv/) in the repo for the scene labels. This repo has DL3DV-270 benchmark with very high quality scenes. Each scene has indoor/outdoor, reflection/transparency/lighting labels. There should be 135 outdoor scenes in this benchmark. We will also provide the performance metrics of some existing methods (nerfacto, instant-ngp, 3D gaussian, mipnerf-360, zipnerf) so that you do not need to re-train it again. If it is urgent for you, you can send an email to ling58@purdue.edu to get the metric csv.

**Comment by ShengCN** [comment]
@shenyehui Our dataset is collected for nerf/3D gaussian training purpose. I would say most of them should be OK to train NeRF. Could you elaborate more about "but it seems that not Not every scenario is suitable for training nerf"? Why do you have this feeling? What are your concerns of using these scenes for your task? 

We cannot guarantee each scene is fully static. If your task is very sensitive to dynamics, I suggest you to refer to the DL3DV-270 benchmark mentioned earlier. Download the benchmark CSV(https://huggingface.co/datasets/DL3DV/DL3DV-Benchmark/blob/main/benchmark-meta.csv), take a look at the "scene" column, and find columns that have the following labels:

> "Botanical-Gardens", "Zoos-Aquariums"

They should satisfy your need. 

If you need more data, you can refer to DL3DV-10K to find relevant data. 

The nature and outdoor is the first order POI, i.e. a big category. We have secondary POIs with more detailed scenes: 
`'Nature & Outdoors': ['Beaches', 'Hiking-Trails', 'Campgrounds', 'Lakes', 'Mountains', 'Farms','Street-View', 'Square'],`
 
You can try to search these keywords to see if they satisfy your need.

**Comment by shenyehui** [comment]
I'm very sorry that my concerns are bothering you, I'll close the issue for now and download your dataset for experimentation, thank you for your patience.

**Comment by ShengCN** [comment]
> I'm very sorry that my concerns are bothering you, I'll close the issue for now and download your dataset for experimentation, thank you for your patience.

Hi @shenyehui, never mind. I hope I addressed your concerns. I am just curious about your thoughts and concerns.

**Comment by shenyehui** [comment]
> > I'm very sorry that my concerns are bothering you, I'll close the issue for now and download your dataset for experimentation, thank you for your patience.
> 
> Hi @shenyehui, never mind. I hope I addressed your concerns. I am just curious about your thoughts and concerns.

Sorry, I'm having problems with image blurring when training nerf-w with the dataset, I don't know enough about 3D vision, should the transform_matrix in transformer.json undergo some kind of transformation before it can be used in nerf training?

**Comment by LuLing06** [comment]
Hi@shenyehui, the transformer.json file is calculated by colmap. It contains the camera intrinsic and extrinsic matrices. You can directly use it for nerf training. 

> > > I'm very sorry that my concerns are bothering you, I'll close the issue for now and download your dataset for experimentation, thank you for your patience.
> > 
> > 
> > Hi @shenyehui, never mind. I hope I addressed your concerns. I am just curious about your thoughts and concerns.
> 
> Sorry, I'm having problems with image blurring when training nerf-w with the dataset, I don't know enough about 3D vision, should the transform_matrix in transformer.json undergo some kind of transformation before it can be used in nerf training?(I mean operations like rotation or mirroring of axes?) Is transform_matrix a matrix in opencv space or opengl space, or is it the pose output by colmap? If it is a matrix in opengl space is it possible to take the inverse matrix and use it directly for nerf training?
