### ISSUE TITLE
Resolution error in some samples

### ISSUE THREAD

**Issue by HeliosZhao** [DL3DV-10K/Dataset#7]
Thanks for the great work!

I noticed that the resolution of some samples is not correct. For example, in the benchmark samples, the 960P images of `07d9f9724ca854fae07cb4c57d7ea22bf667d5decd4058f547728922f909956b` (under `nerfstudio/images_4`)is 480P instead. It seems that the full resolution of the image is 2K instead of 4K and thus the downsampled ones do not match the target size.

**Comment by ShengCN** [comment]
Hi @HeliosZhao, we also noticed this. Hope this does not mess something up. 

Some videos are captured by 2K resolution instead of 4K resolution, which caused this problem. But we think they are also valuable, so we also include them so far. We plan to release the whole dataset first, and then come up with a way to make them more organized.

**Comment by HeliosZhao** [comment]
I think it would be better to name the subfolder with the resolution. For example, use `images_960P` to replace `images_4`, and for those 2K resolution data, just ignore `images_4K`. This might be better to organize the data.

**Comment by ShengCN** [comment]
Thank you for the suggestion! We will consider it.
