### ISSUE TITLE
Undistorted Images

### ISSUE THREAD

**Issue by vincent-leroy** [DL3DV-10K/Dataset#9]
Hello,
Thanks for this awesome dataset. Are the 960x540 images already undistorted or do we need to undistort them ourselves using the OPENCV camera model provided in the colmap files?

**Comment by LuLing06** [comment]
The data is processd by [hloc](https://github.com/cvg/Hierarchical-Localization?tab=readme-ov-file#hloc---the-hierarchical-localization-toolbox) using: 

`ns-process-data video --data $video --output-dir $data --num-frames-target $num_imgs --sfm-tool hloc`

We do not use sepecific distortion correction parameters to process data.  Since the videos are captured by the standard consumer camera (no 360 data involved). It can be directly used for nove view synthesis task.
